#This workflow will run every day, running terraform compute-engine tests
name: Daily compute-engine test run
on:
  schedule:
# At 09:00:00am, every day between Monday and Friday, every month
    - cron: '0 09 * * MON-FRI'

jobs:
  test:
    env:
      IONOS_USERNAME: ${{ secrets.IONOS_VDC_USER_GO_V6 }}
      IONOS_PASSWORD: ${{ secrets.IONOS_VDC_PASSWORD_GO_V6 }}
      TF_ACC: true
      TF_LOG: debug
    strategy:
      matrix:
        go-version: [^1.17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests with compute tag
        run: go test ./ionoscloud -v -failfast -timeout 240m -tags compute
