name: Weekly k8s test run
on:
  schedule:
    # At 09:00:00 - UTC, every week on Monday, every month.
    - cron: '0 09 * * MON'

jobs:
  test:
    env:
      IONOS_USERNAME: ${{ secrets.IONOS_VDC_USER_GO_V6 }}
      IONOS_PASSWORD: ${{ secrets.IONOS_VDC_PASSWORD_GO_V6 }}
      TF_ACC: true
      TF_LOG: debug
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Run tests with 'k8s' tag
        run: go test ./ionoscloud -v -failfast -timeout 240m -tags k8s