name: Test run for server resources
on:
  # This pipeline will fail since there are some known problems, there is no need to run it every
  # two days since we already know that it will fail. When the fix will be made, this 'schedule'
  # section will be uncommented.
  #  schedule:
  #    # At 11:00:00 - UTC, every Monday, Wednesday and Friday
  #    - cron: '0 11 * * MON,WED,FRI'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch on which to run the tests'
        required: true
        default: 'master'

jobs:
  test:
    env:
      IONOS_USERNAME: ${{ secrets.IONOS_VDC_USER_GO_V6 }}
      IONOS_PASSWORD: ${{ secrets.IONOS_VDC_PASSWORD_GO_V6 }}
      TF_ACC: true
      TF_LOG: debug
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || 'master' }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Run tests with `server` tag
        run: go test ./ionoscloud -v -failfast -timeout 240m -tags server
